name: rust-clippy analyze

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "v1-tauri", v0-electron ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: giraffate/clippy-action@v1
      with:
        filter_mode: nofilter
        workdir: ./src-tauri
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}
