name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x,]
        os: [windows-latest,ubuntu-latest,macos-latest]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install modules
      run: |
        # 使用yarn的原因 https://blog.csdn.net/qq_38238956/article/details/124720842
        yarn
    - name: Build
      run: |
        npx browserslist@latest --update-db
        npm run electron:build
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ matrix.os }}
        path: ./dist_electron/*.zip
